globs:
  - "**/*.md"

ignores:
  - ".git/**"
  - "transcript-miner/.venv/**"
  - "wasticlaw-coms/**"
  - "transcript-miner/tests/prompt-engineering/**"
  - "emb-bench/runs/**"
  - "emb-bench/runs_out/**"
  - "AGENTDIARY.md"
  - "TODO.md"
  - "transcript-miner/docs/config.md"

config:
  default: true
  MD001: false
  MD003: false
  MD005: false
  MD007: false
  MD009: false
  MD012: false
  MD013: false
  MD022: false
  MD024: false
  MD025: false
  MD029: false
  MD030: false
  MD031: false
  MD032: false
  MD033: false
  MD034: false
  MD036: false
  MD038: false
  MD040: false
  MD041: false
  MD047: false
  MD058: false
  MD060: false
